services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.27.1
    restart: unless-stopped
    labels:
      - "me.tale.headplane.target=headscale"
    # ports:
    #   - 8080:8080
    volumes:
      - ./container-config:/etc/headscale
      - ./container-data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      reverseproxy-nw:

networks:
  reverseproxy-nw:
    external: true

